### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [qiskit-fall-fest-hackathon-france/qiskit-fall-fest-hackathon-france#1]
"I recently came across your project qiskit-fall-fest-hackathon-france and I noticed that the repository github.com/qiskit-fall-fest-hackathon-france/qiskit-fall-fest-hackathon-france currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by nelimee** [comment]
Hi @cbjuan, 

Most of the code in this repository (mainly the notebooks) has been committed on behalf of other people. As I cannot decide for them, consider this repository to be "Unlicensed" (as is currently the case). This means that no rights are provided, this is basically not open-source code for the moment, and in particular you cannot re-use code from this repository.

If that state ("Unlicensed") changes in the future, I will add the appropriate license file.

**Comment by cbjuan** [comment]
That's fair and probably appropriate. Thanks for the explanation @nelimee !
